# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - blockchainapipf

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        env:
          ADMIN_KEY: ${{secrets.ADMIN_KEY}}
          TESTNET_URL: ${{secrets.TESTNET_URL}}
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          ALGORITHM: ${{secrets.ALGORITHM}}
          SECURITY_KEY: ${{secrets.SECURITY_KEY}}
          INIT_VECTOR: ${{secrets.INIT_VECTOR}}
          STORAGE_KEY: ${{secrets.STORAGE_KEY}}
          CONTRACT_ADDR: ${{secrets.CONTRACT_ADDR}}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blockchainapipf'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E56BCD81F31B46919DA92BE6EB37F578 }}
          package: .
